version: '2'

services:
  
  aygobackend:
    build:
      context: ./aygolabone
      dockerfile: Dockerfile
    ports:
      - "4000"
    depends_on: 
      - dbmongo 

  aygobackend2:
    build:
      context: ./aygolabone
      dockerfile: Dockerfile
    ports:
      - "4000"
    depends_on: 
      - dbmongo 

  aygobackend3:
    build:
      context: ./aygolabone
      dockerfile: Dockerfile
    ports:
      - "4000"
    depends_on: 
      - dbmongo 

  ap-lb-rr:
    build:
      context: ./app-lb-round-robin
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on: 
      - aygobackend
      
  webapp:
    stdin_open: true
    tty: true
    build:
      context: ./aygolaboneclient
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - './aygolaboneclient/:/app'
      - '/app/node_modules' 
    environment:
      - CHOKIDAR_USEPOLLING=true

  dbmongo:
    image: mongo:3.6.1
    container_name: dbmongo 
    volumes:
      - ./aygolabone/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: aygo
    ports:
      - "27017:27017"
    command: mongod

volumes:
  mongodb:
  mongodb_config:
